### PR TITLE
Add missing consts

### PR DESCRIPTION
**Pull request by DanielVandH**

### CODE REVIEW

**Comment by jishnub** [comment]
My understanding was that parametric types are assumed to be `const`s by default, and don't need to be annotated.

**Comment by DanielVandH** [comment]
I there there's a difference, e.g. 

```julia
julia> module Test
       T = Union{Int, Real}
       f(x) = x isa T ? 2.0 : 1
       end
Main.Test

julia> module Test2
       const T = Union{Int, Real}
       f(x) = x isa T ? 2.0 : 1
       end
Main.Test2

julia> @code_warntype Test.f(2.0)
MethodInstance for Main.Test.f(::Float64)
  from f(x) @ Main.Test REPL[1]:3
Arguments
  #self#::Core.Const(Main.Test.f)
  x::Float64
Body::Union{Float64, Int64}
1 ─ %1 = (x isa Main.Test.T)::Bool
└──      goto #3 if not %1
2 ─      return 2.0
3 ─      return 1


julia> @code_warntype Test2.f(2.0)
MethodInstance for Main.Test2.f(::Float64)
  from f(x) @ Main.Test2 REPL[2]:3
Arguments
  #self#::Core.Const(Main.Test2.f)
  x::Float64
Body::Float64
1 ─ %1 = (x isa Main.Test2.T)::Core.Const(true)
└──      goto #3 if not %1
2 ─      return 2.0
3 ─      Core.Const(:(return 1))
```

**Review by dlfivefifty — APPROVED** [review]

**Comment by DanielVandH** [comment]
Interesting, I didn't know about that. It's up to you then, I don't mind if this gets closed. It does have the nice benefit that it at least makes the types consistent with the rest of the types which have a `const`.

**Comment by dlfivefifty** [comment]
I think making it explicit is better

**Pull request merged**
